# Numpy

Numpy is a strong third-party library emphasize on numerical calculation in python.<br>
In short, numpy has a `ndArray` data type, which can process numbers, a large numbers of numbers,faster and more efficiently than `List`.

## Table of Content

### [The Basics](#basics)
 - [Create Array](#create)
 - [Basic Operations](#op)
 - [Indexing, Slicing and Iterating](#index)
 - [Array Manipulation](#man)
 - [Ordering](#order)
 - [Basic Statistics](#stat)
 
### [Simple Comparison](#compare)
 - [Code Complexity](#code)
 - [Speed](#speed)

### [Further Resources](#resource)

<a id=basics></a>
## The Basics

<a id=create></a>
### Create Array

First, we will have to import `numpy` library. In python, it is
```python
import numpy as np
```
Here, `np` is a convention that abbreviate `numpy`. So that, later in that program, we just need to type `np` instead of `numpy`. 

There are many ways to create a numpy array.
First, let's create an array from list.
```python
array = np.array(list)
```

In [70]:
import numpy as np

# Let's Create an array
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

# Print Out the Array
print(array)
print(type(array))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [72]:
# The attributes in `ndarray`.
# Check dtype of the array
print(array.dtype)

# Check item size (number of Bytes)
print(array.itemsize)

# Check array Size
print(array.size)

# Check number of axis
print(array.ndim)

# Check shape of array
print(array.shape)

# Check the byte of each element
print(array.nbytes)

int64
8
10
2
(2, 5)
80


We can also create array from range. `np.arange` function is just like `range()` in built-in python function.
```python
np.arange([start,] stop[, step,], dtype=None)
```
The square bracket '[ ]' here mean it has the default value set up. If we do not specify the value, it will take the default value.

eg. the value for **start** argument is **0**.

In [21]:
# Let's create another array with function

array = np.arange(20)
print(array)

array = np.arange(2, 20, 2)
print(array)

# start and stop same
array = np.arange(2, 2, 2)
print(array)

# Reverse
array = np.arange(40, 20, -2)
print(array)

# Float points
array = np.arange(0, 2, 0.3)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10 12 14 16 18]
[]
[40 38 36 34 32 30 28 26 24 22]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


But, with `np.arange`, we could not control the number of element in that array. So:
```python
array = np.linspace(start, stop, num=50)
```

Here, we could specify the number of element between the range that we want.

In [68]:
# Create with the count of array wanted
array = np.linspace(0, 2, 5)
print(array)

# reverse
array = np.linspace(20, 2, 20)
print(array)

# start and end same
array = np.linspace(20, 20, 5)
print(array)

(50,)
[0.  0.5 1.  1.5 2. ]
[20.         19.05263158 18.10526316 17.15789474 16.21052632 15.26315789
 14.31578947 13.36842105 12.42105263 11.47368421 10.52631579  9.57894737
  8.63157895  7.68421053  6.73684211  5.78947368  4.84210526  3.89473684
  2.94736842  2.        ]
[20. 20. 20. 20. 20.]



Or, we could just create array from the fly just describe the shape of array that we want.
```python
zeros = np.zeros(shape, dtype, order='C')
ones = np.ones(shape, dtype, order='C')
empty = np.empty(shape, dtype, order='C')
```

In [23]:
# Initialize array for place holder
array = np.zeros((5,5))
print(array)
print(array.dtype)

# Default dtype is float64
array = np.zeros((3,3), dtype=np.uint8)
print(array)
print(array.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]
 [0 0 0]]
uint8


In [29]:
array = np.ones((5,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
array = np.empty((5,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# Create with existing Variable

list_var = [1, 2, 3, 4]
array = np.array(list_var)
print(list_var, array)

[1, 2, 3, 4] [1 2 3 4]


In [28]:
nested_list = [[1, 2, 3], [4, 5, 6]]
nested_array = np.array(nested_list)

print(nested_list, '\n', nested_array)
print(nested_array.dtype)

[[1, 2, 3], [4, 5, 6]] 
 [[1 2 3]
 [4 5 6]]
int64


In [29]:
list_var = [1., 2., 3.]
array = np.array(list_var)

print(type(list_var[0]), array.dtype)
print(list_var, array)

<class 'float'> float64
[1.0, 2.0, 3.0] [1. 2. 3.]


<a id=op></a>
### Basic Operations

In [1]:
import numpy as np
# Simple Arithmetic Operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

print("Addition of two array : \t", array_a + array_b)
print("Subtraction of two array : \t", array_a - array_b)
print("Multiplication of two array : \t", array_a * array_b)
print("Division of two array : \t", array_a / array_b)

Addition of two array : 	 [5 7 9]
Subtraction of two array : 	 [-3 -3 -3]
Multiplication of two array : 	 [ 4 10 18]
Division of two array : 	 [0.25 0.4  0.5 ]


There are many scientific functions....

In [4]:
# Or we could apply basic math functions [sin, cos] to arrays.
sine_array = np.sin(array_a)
cos_array = np.cos(array_a)
exp_array = np.exp(array_a)
log_array = np.log(array_a)

print(sine_array, '\n', cos_array, '\n', exp_array, '\n', log_array)

[0.84147098 0.90929743 0.14112001] 
 [ 0.54030231 -0.41614684 -0.9899925 ] 
 [ 2.71828183  7.3890561  20.08553692] 
 [0.         0.69314718 1.09861229]


In [8]:
# We could check elements with threshold value
array_b = np.array([4, 5, 6])
check = array_b >= 5
print(check)

[False  True  True]


<a id=index></a>
### Indexing, Slicing and Iterating

![](animations/index_animation.gif)

In [60]:
a = np.arange(0, 20, 2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [61]:
# Index : Select sepecific element
element = a[1]
print(element)

2


In [62]:
# Slicing : Select Range of element
range_element = a[1:5]
print(range_element)

[2 4 6 8]


In [65]:
# Reverse Slicing
reverse_element = a[8:2:-1]
print(reverse_element)

[16 14 12 10  8  6]


In [67]:
# Iteration
for i in a:
    print(i)

0
2
4
6
8
10
12
14
16
18


<a id=man></a>
### Array Manipulation

We could manipulate shape of array in numpy.
![](animations/stacking_animation.gif)

In [68]:
array = np.zeros((3,3))
print(array.shape)

(3, 3)


In [70]:
# This method create a new axis and stack in that axis
dstack = np.dstack((array, array))
print(dstack.shape)

(3, 3, 2)


In [71]:
hstack = np.hstack((array, array))
print(hstack.shape)

(3, 6)


<a id=order></a>
### Ordering

Sort or find the **Max**, **Min** value in the array.
![](animations/min_max_animation.gif)

In [85]:
array = np.array([2, 1, 2, 5, 2, 100, 2, 99, 12])
sorted_array = np.sort(array)
min_value = np.min(array)
argmin = np.argmin(array)
max_value = np.max(array)
argmax = np.argmax(array)

print("Original Array : \t\t\t", array)
print("Sorted Array : \t\t\t\t", sorted_array)
print("Minimum value in Array : \t\t", min_value)
print("Index where minimum value exists : \t", argmin)
print("Maximum value in Array : \t\t", max_value)
print("Index where maximum value exists : \t", argmax)

Original Array : 			 [  2   1   2   5   2 100   2  99  12]
Sorted Array : 				 [  1   2   2   2   2   5  12  99 100]
Minimum value in Array : 		 1
Index where minimum value exists : 	 1
Maximum value in Array : 		 100
Index where maximum value exists : 	 5


<a id=stat></a>
### Basic Statistics

We could find the basic statistics value `Mean`, `Standard Deviation` and `Variance` in the array.

In [9]:
array = np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
mean = np.mean(array)
std = np.std(array)
var = np.var(array)

print(f"Mean : \t\t\t{mean}\nStandard Deviation : \t{std:.2f}\nVariance : \t\t{var}")

Mean : 			9.5
Standard Deviation : 	5.77
Variance : 		33.25


<a id=compare></a>
### Simple Comparison



Let's Compare the calculation time needed between List and ndarray.

In [44]:
a = [[1, 2, 3], [4, 5, 6]]
print(a)
print()

array_a = np.array(a)
print(array_a)
print()

# Add 1: to list, We have to use for loop to get each element in list.
result = []
for i in a:
    result_ = []
    for j in i:
        result_.append(j+1)
    result.append(result_)
print(result)
print()

# Add 1: to array, numpy use broadcasting to get every element in array.
array_a += 1
print(array_a)

[[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]]

[[2, 3, 4], [5, 6, 7]]

[[2 3 4]
 [5 6 7]]


In [45]:
# Let's try to compare for large numbers.
np_array = np.arange(1000000)
np_array = np.reshape(np_array, (50,100, -1))

# We get (100,100,100) elements in that array
print(np_array.shape)

(50, 100, 200)


In [47]:
# We can convert from ndarray object to list object with
list_obj = np_array.tolist()
print(len(list_obj[0][0]))
print(type(list_obj))

200
<class 'list'>


<a id=code></a>
#### Code Complexity

In [48]:
# Add 1: to list
for i in range(len(list_obj)):
    for j in range(len(list_obj[0])):
        for k in range(len(list_obj[0][0])):
            list_obj[i][j][k] += 1

In [49]:
# Add 1: to Array
np_array += 1

<a id=speed></a>
#### Speed

In [50]:
%%timeit
np_array = np.arange(1000000)
np_array = np.reshape(np_array, (50,100, -1))
np_array+=1

3.3 ms ± 61 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
%%timeit
# Add 1: to list
for i in range(len(list_obj)):
    for j in range(len(list_obj[0])):
        for k in range(len(list_obj[0][0])):
            list_obj[i][j][k] += 1

190 ms ± 4.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Every time you run, the value might be a little different, but:
![](images/run_test.png)

In array, it only costs `4.61ms` when in list it costs `186ms`.<br>
That is so much faster in numpy.

<a id=resources></a>
## Further Resources

If you wanna know about Numpy array, please visit this official Numpy [documentation](https://numpy.org/doc/1.19/user/quickstart.html). And also this blog post about 